[alias]     # command aliases
b = "build"
br = "build --release"
c = "check"
t = "test"
r = "run"
i = "install --path ."
rr = "run --release"
w = "clippy -- -D warnings"
recursive_example = "rr --example recursions"
space_example = ["run", "--release", "--", "\"command list\""]

[future-incompat-report]
frequency = 'always' # When to display a notification about a future incompatible report

